/**
 * Created by prathamesh on 7/2/17.
 */
public class EvenFibonacci {

    private static int [] fibs = new int [100];

    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    public static void main(String [] args) {
        int sum = 0;
        int limit = 4000000;
        for (int i = 0; i<100; i++) {
            int f = getFib(i);
            if (f >= limit) {
                break;
            }
            if (f % 2 == 0 && f < limit) {
                sum += f;
            }
        }
        System.out.println(sum);
    }

    private static int getFib(int i) {
        if (i == 0) {
            return 0;
        }
        if (i == 1) {
            return 1;
        }
        if (fibs[i] != 0) {
            return fibs[i];
        }
        fibs[i] = getFib(i-1) + getFib(i-2);
        return fibs[i];
    }
}
